version: "3"
services:
  coupon-example-mysql:
    container_name: coupon-example-mysql
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: coupon_example
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3316:3306"
