version: "3"
services:
  mysql:
    container_name: coupon-example-mysql
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: coupon_example
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3316:3306"
  redis:
    container_name: coupon-example-redis
    image: redis:7.0.4
    command: redis-server --port 6379
    hostname: redis_standalone
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
